name: Test Clients
on:
  push:
    branches:
      - main
      - beta
      - ci

jobs:
  generate:
    name: Test Clients
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          path: clients
          #ref: main

      - name: Test
        working-directory: clients
        env:
          M3O_API_TOKEN: ${{ secrets.M3O_API_TOKEN }}
        run: |
          # stream is temporarily excluded as it hangs forever because test does not close connection
          # @todo remove "idempotent: true" from stream example
          find . -name ".run" | grep -v stream | xargs -n1 dirname | xargs -n1 go run
